server:
  host: 'localhost'
  port: 7700
  debug: true

database:
  host: 'localhost'
  user: 'qogita'
  password: 'qogita1234'
  db: 'QOGITA'

cors:
  resources:
    "/api/*":
      origins: "*"
  methods:
    - 'GET'
    - 'POST'

logging:
  level: 'WARNING'